[package]
name = "lovelace"
authors = ["Ada F. <https://github.com/ErisianArchitect>"]
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
rust-version = "1.98"

[target.'cfg(unix)'.dependencies]
rustix = { version = "1.1.5", features = ["mm", "param"] }

[target.'cfg(windows)'.dependencies]

[dependencies]
